# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master
    
#resources:
#  - name: pem_keys
#    type: integration
#    integration: "SONAR-SERVER"

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - Access_key=$(shipctl get_integration_resource_field SONAR-SERVER "Key")

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    #- shippable_retry npm install
    #- mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    #- pushd $TESTS_LOC_DIR
    #- $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    #- $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    #- $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    #- popd
    - echo "hiiiiiiiiiiii"
    - date
    - ip r
    - echo "-----BEGIN RSA PRIVATE KEY-----
            MIIEowIBAAKCAQEA47KL1nQSVtet04e50rtYVmxp/IzMnhXQxVt0rlW0nl19LlBL71XYwBSDJgqG
            5XZ6MtEZ2NXyRjlMY0fVvVwYZ7kCduKe2RmFXXWHUe6DhaXKfW82PeCznjuk6kuj0PFrrPCBEy+G
            emjsJCa3/h7HxmDy8EQwBOaD/SubYwiJNT6XtvO88JPNfgj8acUG0Uz4WfrdR2p3GYopvZaLez92
            K9veJphjKF9YozpQvEGvOdemoE766pLDohullROo+/f4ELJvvowRQxnOIwCQtKdCu9V5J2fPypfD
            0RQtnV2bk92+J/OhFmP2FNbTln7oTYejk93B+bQ27NG1MRLFRv/57QIDAQABAoIBAQCGwIazbtPf
            oxqTQhK93POlidmbhbQepmh8M+i0t7IBuvA3dXvK83IoErueysIUkG43Hrp+MfeEiapkYwHiY9tp
            nvsPYoSBlPHxYnmoClC5ymkwnJ1sN0v1i/TIV+Vl5UpE+bxZn1mlneyKZIOlF5BBHeUIPkJw0/8u
            2BzImiehYwC9+WHrvxAnuie2sRqBCKJ9270/EbJH6QN3MKniE9zG977Pm64VvTo+duw/WyUoXRMZ
            Ji6AJrZW3KFwE7uleQtrEOK3KfXhgMMWwT6scYdA4h6FLwxkuk3WI+S5CO2b/0BcUfQlHLFsOR6Y
            6aKy27/wmCS9C7QExTrHdNnIJS1dAoGBAPjlZ0Nr8Ji0vHeTRPwNb7MpdQxoi4eMRu9ml1hG53hZ
            1VVBsH0UoFIQYecpq20rA/sdFr1HeeA6NeywIA7Uuf8/y6xw5bsC9P0df4UOQv2d8AIg8XgiLm0j
            ITxxlemMZEQXzB7WB2ZE5b7tDm/Lj4OOPQZoP/MTwtL01KJcDL3zAoGBAOoyQG5eeT2ttqHO9q8/
            lvBHD9aKqzSVE12BgoDJ0EDc2n26+59+zdgJHKFfDeiIOLUMfq1J7gcwnlKg1wl9LrgLcGyV9CL3
            4k5ZIv4HUzxyl2RFcL3Lmcae8PZ8IVAIP2jxuwiEpQt5FsHq/L2E50uQKj0OKuFfPpTzx0RAEgCf
            AoGAPg1bcFix1DCDKECkGz7yUTWNw/kwiCu156upIc4TmVK0OBw3dwe0bKE+91XRMldeF7YJ3Ei8
            nuWEWi0S4P+yG2v5SFWhQL2c/JnlF/QVSYudsboq2WuULYtrltkuqdphiQRx1GJB2AJnUPFi/wY+
            Emtc1YMaJm0Pzm5RsOTIHHcCgYB9+9BrTwkbo/JGMybC+YtB8IhVmj0lSTikqYHBtE8CRYyH7Gll
            0Hn9SFGNgavitj0DMBiJMecJGR9iRcHICf5y5TxyPWyazwx/pzXKv7gIIYDNYQmYIAm2LlRj1Dy7
            Z+RsmPVLTMfYVyhl4vpZHUCrhn8iXxe0K19oE4fTcD/+8wKBgB96f5ZZuD0et2cNV+i1Yc/hcYwv
            x+0ULNJGZysQdCA6XwyAuVWO9nb4WhOyyIf69F1cIg5T0DVCaEpivf3/PReXTFxOzXpiOo3RNDR6
            rrYIJVllk1dIb5PD5f0bWieNUAlA3Y3FiDeEwPTLY590/mTPVgLFjvR4aSEI/waOw2XU
            -----END RSA PRIVATE KEY-----" >> Neov-nvirg.pem
    - chmod 400 Neov-nvirg.pem
    - ls -l 
    - pwd
    - yum install -y ping
    #- telnet 54.90.245.228 22
    - ping 54.90.245.228 -c 2
    - ssh -vvv -i Neov-nvirg.pem centos@ec2-54-90-245-228.compute-1.amazonaws.com

#jobs:
#  - name: myCustomJob
#    type: runSh
#    integrations:
#      - SONAR-SERVER
#    steps:
#      - TASKS:
#        - script: shipctl get_integration_keys "SONAR-SERVER"

resources:
  - name: pem_keys
    type: integration
    integration: "SONAR-SERVER"

jobs:
  - name: deploy_war_vm_ans
    type: runSh
    steps:
      - IN: pem_keys
        switch: off
      - TASK:
          name: deploy_war
          script:
            - echo "$(shipctl get_integration_resource_field SONAR-SERVER "Keys")"

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never
