# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master
    
# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - Access_key=$(shipctl get_integration_resource_field SONAR-SERVER "Key")

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - echo "hiiiiiiiiiiii"
    - date
    - ip r
      #- echo "-----BEGIN RSA PRIVATE KEY-----
      #-      MIIEowIBAAKCAQEA47KL1nQSVtet04e50rtYVmxp/IzMnhXQxVt0rlW0nl19LlBL71XYwBSDJgqG
      #-      5XZ6MtEZ2NXyRjlMY0fVvVwYZ7kCduKe2RmFXXWHUe6DhaXKfW82PeCznjuk6kuj0PFrrPCBEy+G
      #-      emjsJCa3/h7HxmDy8EQwBOaD/SubYwiJNT6XtvO88JPNfgj8acUG0Uz4WfrdR2p3GYopvZaLez92
      #-      K9veJphjKF9YozpQvEGvOdemoE766pLDohullROo+/f4ELJvvowRQxnOIwCQtKdCu9V5J2fPypfD
      #-      0RQtnV2bk92+J/OhFmP2FNbTln7oTYejk93B+bQ27NG1MRLFRv/57QIDAQABAoIBAQCGwIazbtPf
      #-      oxqTQhK93POlidmbhbQepmh8M+i0t7IBuvA3dXvK83IoErueysIUkG43Hrp+MfeEiapkYwHiY9tp
      #-      nvsPYoSBlPHxYnmoClC5ymkwnJ1sN0v1i/TIV+Vl5UpE+bxZn1mlneyKZIOlF5BBHeUIPkJw0/8u
      #-      2BzImiehYwC9+WHrvxAnuie2sRqBCKJ9270/EbJH6QN3MKniE9zG977Pm64VvTo+duw/WyUoXRMZ
      #-      Ji6AJrZW3KFwE7uleQtrEOK3KfXhgMMWwT6scYdA4h6FLwxkuk3WI+S5CO2b/0BcUfQlHLFsOR6Y
      #-      6aKy27/wmCS9C7QExTrHdNnIJS1dAoGBAPjlZ0Nr8Ji0vHeTRPwNb7MpdQxoi4eMRu9ml1hG53hZ
      #-      1VVBsH0UoFIQYecpq20rA/sdFr1HeeA6NeywIA7Uuf8/y6xw5bsC9P0df4UOQv2d8AIg8XgiLm0j
      #-      ITxxlemMZEQXzB7WB2ZE5b7tDm/Lj4OOPQZoP/MTwtL01KJcDL3zAoGBAOoyQG5eeT2ttqHO9q8/
      #-      lvBHD9aKqzSVE12BgoDJ0EDc2n26+59+zdgJHKFfDeiIOLUMfq1J7gcwnlKg1wl9LrgLcGyV9CL3
      #-      4k5ZIv4HUzxyl2RFcL3Lmcae8PZ8IVAIP2jxuwiEpQt5FsHq/L2E50uQKj0OKuFfPpTzx0RAEgCf
      #-      AoGAPg1bcFix1DCDKECkGz7yUTWNw/kwiCu156upIc4TmVK0OBw3dwe0bKE+91XRMldeF7YJ3Ei8
      #-      nuWEWi0S4P+yG2v5SFWhQL2c/JnlF/QVSYudsboq2WuULYtrltkuqdphiQRx1GJB2AJnUPFi/wY+
      #-      Emtc1YMaJm0Pzm5RsOTIHHcCgYB9+9BrTwkbo/JGMybC+YtB8IhVmj0lSTikqYHBtE8CRYyH7Gll
      #-      0Hn9SFGNgavitj0DMBiJMecJGR9iRcHICf5y5TxyPWyazwx/pzXKv7gIIYDNYQmYIAm2LlRj1Dy7
      #-      Z+RsmPVLTMfYVyhl4vpZHUCrhn8iXxe0K19oE4fTcD/+8wKBgB96f5ZZuD0et2cNV+i1Yc/hcYwv
      #-      x+0ULNJGZysQdCA6XwyAuVWO9nb4WhOyyIf69F1cIg5T0DVCaEpivf3/PReXTFxOzXpiOo3RNDR6
      #-      rrYIJVllk1dIb5PD5f0bWieNUAlA3Y3FiDeEwPTLY590/mTPVgLFjvR4aSEI/waOw2XU
      #-      -----END RSA PRIVATE KEY-----" >> Neov-nvirg.pem
      #- chmod 400 Neov-nvirg.pem
      #- ls -l 
      #- pwd
      #- export AWS_ACCESS_KEY_ID=$(shipctl get_integration_resource_field dr_aws "Keys")
      #- ./ssh.sh
    #- apt update -y
    #- apt install -y wc
    #- chmod 400 /root/src/github.com/govind-neova/basic-project/Neov-nvirg.pem
    #- export AWS_SECRET_ACCESS_KEY=$(shipctl get_integration_field dr_aws )
    #- ssh -i /root/src/github.com/govind-neova/basic-project/Neov-nvirg.pem ubuntu@ec2-54-235-6-9.compute-1.amazonaws.com -t "cd /home/ubuntu/git-projects/scripts-repository && ./sonar.sh https://github.com/govind-neova/puppeteer.git govind-test"
    #- sudo -u  sonarqube bash -c ' sh /opt/sonarqube/bin/linux-x86-64/sonar.sh start '
    #- export PUBLIC_SSH_KEY=$(shipctl get_integration_resource_field pem_cd_war_vm "Keys")
    #- echo $PUBLIC_SSH_KEY
    #- export PEM_KEY_PATH="/tmp/pem_key.pem"
    #- echo $PEM_KEY_PATH
    #- echo $PEM_CD_WAR_VM_KEYPATH
    #- cp $PEM_CD_WAR_VM_KEYPATH /tmp/pem_key.pem
    #- private_key = "${file(var.ec2privatekey)}"
    #- echo $private_key
    #- ./ssh.sh

resources:
  - name: pem_cd_war_vm
    type: integration
    integration: "drship_aws_pem"

jobs:
  - name: deploy_war_vm_ans
    type: runSh
    steps:
      - IN: pem_cd_war_vm
        switch: IN
      - TASK:
          name: deploy_war
          script:
            - export pem_key_name=$(shipctl get_integration_resource_field pem_cd_war_vm "Keys")
            - cp $PEM_CD_WAR_VM_KEYPATH /tmp/pem_key.pem
            - ./ssh.sh

      #integrations:

  # http://docs.shippable.com/ci/shippableyml/#notifications
  notifications:
  # turning of email for PR builds, get notified only on failure and change in status
  # http://docs.shippable.com/integrations/notifications/email/
    - integrationName: email
      type: email
      on_success: change
      on_failure: always
      on_pull_request: never
